import type { ITable, ITableWithReserve } from '../types';

export const tables: ITable[] = [
  {
    id: 5,
    count: 4,
    number: 307,
    priority: 5,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-04T19:58:23.1906179',
    floorId: 1,
    floor: {
      id: 1,
      name: 'Веранда',
      priority: 1,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 6,
    count: 2,
    number: 308,
    priority: 6,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-04T20:02:41.6710685',
    floorId: 1,
    floor: {
      id: 1,
      name: 'Веранда',
      priority: 1,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table9',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 7,
    count: 4,
    number: 309,
    priority: 7,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-04T20:19:02.0757314',
    floorId: 1,
    floor: {
      id: 1,
      name: 'Веранда',
      priority: 1,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 8,
    count: 2,
    number: 310,
    priority: 8,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-04T20:20:32.6207756',
    floorId: 1,
    floor: {
      id: 1,
      name: 'Веранда',
      priority: 1,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table9',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 9,
    count: 6,
    number: 311,
    priority: 9,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-04T20:21:36.025054',
    floorId: 1,
    floor: {
      id: 1,
      name: 'Веранда',
      priority: 1,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table15',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 10,
    count: 6,
    number: 312,
    priority: 10,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-04T20:22:01.0479398',
    floorId: 1,
    floor: {
      id: 1,
      name: 'Веранда',
      priority: 1,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table15',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 11,
    count: 8,
    number: 313,
    priority: 11,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-04T20:22:31.3958036',
    floorId: 1,
    floor: {
      id: 1,
      name: 'Веранда',
      priority: 1,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table4',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 12,
    count: 6,
    number: 300,
    priority: 12,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-04T20:23:10.430807',
    floorId: 1,
    floor: {
      id: 1,
      name: 'Веранда',
      priority: 1,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table2',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 13,
    count: 2,
    number: 301,
    priority: 13,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-04T20:23:45.2445828',
    floorId: 1,
    floor: {
      id: 1,
      name: 'Веранда',
      priority: 1,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table8',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 14,
    count: 2,
    number: 302,
    priority: 14,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-04T20:24:23.1323034',
    floorId: 1,
    floor: {
      id: 1,
      name: 'Веранда',
      priority: 1,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table8',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 15,
    count: 4,
    number: 303,
    priority: 15,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-04T20:24:38.5637041',
    floorId: 1,
    floor: {
      id: 1,
      name: 'Веранда',
      priority: 1,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 16,
    count: 4,
    number: 304,
    priority: 16,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-04T20:25:05.1242723',
    floorId: 1,
    floor: {
      id: 1,
      name: 'Веранда',
      priority: 1,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 17,
    count: 2,
    number: 305,
    priority: 17,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-04T20:25:20.5432469',
    floorId: 1,
    floor: {
      id: 1,
      name: 'Веранда',
      priority: 1,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table8',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 18,
    count: 2,
    number: 306,
    priority: 18,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-04T20:25:47.1577496',
    floorId: 1,
    floor: {
      id: 1,
      name: 'Веранда',
      priority: 1,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table8',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 246,
    count: 4,
    number: 3081,
    priority: 19,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-12-29T22:20:09.3276147',
    floorId: 1,
    floor: {
      id: 1,
      name: 'Веранда',
      priority: 1,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 239,
    count: 4,
    number: 11,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-12-29T22:15:46.5295747',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 240,
    count: 4,
    number: 171,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-12-29T22:16:44.7488527',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 241,
    count: 4,
    number: 221,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-12-29T22:17:06.8032791',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table10',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 249,
    count: 2,
    number: 571,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-12-30T20:49:31.3880237',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table9',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 52,
    count: 2,
    number: 1,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:13:17.7686187',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table8',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 53,
    count: 2,
    number: 2,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:13:34.3165009',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table8',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 54,
    count: 4,
    number: 3,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:14:05.9441581',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 55,
    count: 4,
    number: 4,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:14:24.9482286',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 56,
    count: 3,
    number: 5,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:15:07.6394342',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table16',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 57,
    count: 6,
    number: 6,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:15:29.4765799',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table15',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 58,
    count: 8,
    number: 101,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:18:17.0834672',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table1',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 59,
    count: 8,
    number: 102,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:18:44.6085486',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table1',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 60,
    count: 8,
    number: 103,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:18:54.0326911',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table4',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 61,
    count: 10,
    number: 104,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:19:11.6302768',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table14',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 62,
    count: 6,
    number: 105,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:19:38.307278',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table15',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 63,
    count: 6,
    number: 106,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:20:03.8727065',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table15',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 64,
    count: 6,
    number: 107,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:20:05.1589538',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table15',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 65,
    count: 6,
    number: 108,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:20:06.0516707',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table15',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 66,
    count: 4,
    number: 562,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:21:18.3453193',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 67,
    count: 4,
    number: 12,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:21:23.5564828',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 68,
    count: 4,
    number: 13,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:21:24.4218177',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 69,
    count: 6,
    number: 14,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:22:20.4032993',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table12',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 70,
    count: 8,
    number: 15,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:22:52.6264301',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table1',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 71,
    count: 12,
    number: 16,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:23:17.8430794',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table13',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 72,
    count: 4,
    number: 17,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:23:34.0738939',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 73,
    count: 5,
    number: 21,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:24:16.0435271',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table3',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 74,
    count: 4,
    number: 25,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:24:35.9824738',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 75,
    count: 4,
    number: 22,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:25:07.654786',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table10',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 76,
    count: 4,
    number: 26,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:26:44.221201',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table10',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 77,
    count: 4,
    number: 23,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:28:55.9551073',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 78,
    count: 4,
    number: 24,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:29:22.7262703',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 79,
    count: 10,
    number: 27,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:29:32.986924',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table14',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 80,
    count: 4,
    number: 28,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:30:06.193249',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 81,
    count: 6,
    number: 29,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:30:21.5768409',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table2',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 82,
    count: 8,
    number: 48,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:31:22.9683326',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table4',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 83,
    count: 8,
    number: 41,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:31:55.0674998',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table4',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 84,
    count: 3,
    number: 47,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:32:04.223981',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table6',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 85,
    count: 4,
    number: 46,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:32:49.096821',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 86,
    count: 4,
    number: 45,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:33:25.5399626',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 87,
    count: 4,
    number: 44,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:33:50.9172674',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 88,
    count: 4,
    number: 43,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:33:51.6977666',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 89,
    count: 3,
    number: 42,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:33:52.2978688',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table6',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 90,
    count: 8,
    number: 30,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:36:39.3912929',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table4',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 91,
    count: 6,
    number: 31,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:37:02.9941518',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table2',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 92,
    count: 4,
    number: 53,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:37:38.0332213',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 93,
    count: 4,
    number: 52,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:38:20.1518528',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 94,
    count: 4,
    number: 54,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:38:21.3026624',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 95,
    count: 4,
    number: 55,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:38:22.3508952',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 96,
    count: 4,
    number: 56,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:38:23.4838605',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 97,
    count: 2,
    number: 51,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:39:01.5845416',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table9',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 98,
    count: 2,
    number: 57,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:39:19.8549117',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table9',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 99,
    count: 4,
    number: 33,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-06T14:04:52.7737159',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 100,
    count: 4,
    number: 261,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-06T14:08:03.2454349',
    floorId: 2,
    floor: {
      id: 2,
      name: '1 Этаж',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table10',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 103,
    count: 4,
    number: 2451,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-11-06T16:26:11.0354114',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 23,
    count: 12,
    number: 272,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T20:50:22.5999149',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table13',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 24,
    count: 2,
    number: 262,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T20:52:11.4679556',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table8',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 25,
    count: 8,
    number: 261,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T20:52:28.4368719',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table1',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 26,
    count: 4,
    number: 253,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T20:52:54.2134322',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 27,
    count: 8,
    number: 252,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T20:53:29.656636',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table1',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 28,
    count: 8,
    number: 251,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T20:54:08.205333',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table4',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 29,
    count: 4,
    number: 245,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T20:54:42.1252819',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 31,
    count: 4,
    number: 243,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T20:55:39.8576683',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 32,
    count: 4,
    number: 244,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T20:57:08.9295112',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 33,
    count: 8,
    number: 242,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T20:57:30.0908017',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table1',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 34,
    count: 8,
    number: 241,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T20:58:48.7715855',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table4',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 35,
    count: 6,
    number: 234,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T20:59:15.3159564',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table2',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 36,
    count: 5,
    number: 233,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T20:59:47.3777466',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table3',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 37,
    count: 4,
    number: 235,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:00:10.8885495',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table10',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 38,
    count: 4,
    number: 236,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:01:11.7389184',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table10',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 39,
    count: 8,
    number: 232,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:01:28.4454323',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table1',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 40,
    count: 8,
    number: 231,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:02:34.0035158',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table4',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 41,
    count: 4,
    number: 214,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:03:27.0223682',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 42,
    count: 4,
    number: 213,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:05:16.670497',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 43,
    count: 4,
    number: 212,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:05:34.92038',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 44,
    count: 4,
    number: 211,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:05:44.5743617',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table11',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 45,
    count: 6,
    number: 222,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:05:58.0456026',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table15',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 46,
    count: 6,
    number: 221,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:07:52.1298976',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table15',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 47,
    count: 4,
    number: 203,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:09:19.1719499',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table10',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 48,
    count: 6,
    number: 204,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:09:52.9876909',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table2',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 49,
    count: 4,
    number: 205,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:09:57.306628',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table10',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 50,
    count: 5,
    number: 202,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:11:06.573105',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table3',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 51,
    count: 2,
    number: 201,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T21:11:25.4707002',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table8',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 242,
    count: 4,
    number: 275,
    priority: 2,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-12-29T22:17:53.393419',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table1',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 243,
    count: 4,
    number: 276,
    priority: 2,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-12-29T22:18:28.326515',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table1',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 244,
    count: 4,
    number: 2351,
    priority: 2,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-12-29T22:18:41.9628375',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table10',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 245,
    count: 4,
    number: 2361,
    priority: 2,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-12-29T22:19:07.4541727',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table10',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 1,
    count: 10,
    number: 273,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-08-29T20:24:35.2036312',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table14',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 2,
    count: 10,
    number: 274,
    priority: 2,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-08-29T20:24:35.2036634',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table14',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 3,
    count: 10,
    number: 271,
    priority: 3,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-08-29T20:24:35.203664',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table14',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 4,
    count: 2,
    number: 263,
    priority: 4,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-08-29T20:24:35.2036644',
    floorId: 3,
    floor: {
      id: 3,
      name: '2 Этаж',
      priority: 3,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table8',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 247,
    count: 4,
    number: 404,
    priority: 2,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-12-29T22:20:31.8343754',
    floorId: 4,
    floor: {
      id: 4,
      name: 'Веранда вип',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table1',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 248,
    count: 4,
    number: 405,
    priority: 2,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-12-29T22:20:40.1401958',
    floorId: 4,
    floor: {
      id: 4,
      name: 'Веранда вип',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table1',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 19,
    count: 8,
    number: 400,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T20:45:08.3839956',
    floorId: 4,
    floor: {
      id: 4,
      name: 'Веранда вип',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table1',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 20,
    count: 8,
    number: 401,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T20:47:17.6898414',
    floorId: 4,
    floor: {
      id: 4,
      name: 'Веранда вип',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table1',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 21,
    count: 8,
    number: 402,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T20:47:31.4909595',
    floorId: 4,
    floor: {
      id: 4,
      name: 'Веранда вип',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table1',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 22,
    count: 8,
    number: 403,
    priority: 1,
    canGuestReserve: true,
    isActive: true,
    createdTime: '2024-09-05T20:47:40.8817904',
    floorId: 4,
    floor: {
      id: 4,
      name: 'Веранда вип',
      priority: 2,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table1',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 250,
    count: 1,
    number: 1,
    priority: 1,
    canGuestReserve: false,
    isActive: true,
    createdTime: '2025-01-25T16:43:08.3694006',
    floorId: 16,
    floor: {
      id: 16,
      name: '41 стол',
      priority: 5,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table17',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 251,
    count: 1,
    number: 2,
    priority: 1,
    canGuestReserve: false,
    isActive: true,
    createdTime: '2025-01-25T16:43:08.3693758',
    floorId: 16,
    floor: {
      id: 16,
      name: '41 стол',
      priority: 5,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table17',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 252,
    count: 1,
    number: 3,
    priority: 1,
    canGuestReserve: false,
    isActive: true,
    createdTime: '2025-01-25T16:44:16.1082077',
    floorId: 16,
    floor: {
      id: 16,
      name: '41 стол',
      priority: 5,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table17',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 253,
    count: 1,
    number: 4,
    priority: 1,
    canGuestReserve: false,
    isActive: true,
    createdTime: '2025-01-25T16:44:30.061104',
    floorId: 16,
    floor: {
      id: 16,
      name: '41 стол',
      priority: 5,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table17',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 254,
    count: 1,
    number: 5,
    priority: 1,
    canGuestReserve: false,
    isActive: true,
    createdTime: '2025-01-25T16:44:38.4250129',
    floorId: 16,
    floor: {
      id: 16,
      name: '41 стол',
      priority: 5,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table17',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 255,
    count: 1,
    number: 6,
    priority: 1,
    canGuestReserve: false,
    isActive: true,
    createdTime: '2025-01-25T16:44:52.3725629',
    floorId: 16,
    floor: {
      id: 16,
      name: '41 стол',
      priority: 5,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table17',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 256,
    count: 1,
    number: 7,
    priority: 1,
    canGuestReserve: false,
    isActive: true,
    createdTime: '2025-01-25T16:45:04.03204',
    floorId: 16,
    floor: {
      id: 16,
      name: '41 стол',
      priority: 5,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table17',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
  {
    id: 257,
    count: 1,
    number: 8,
    priority: 1,
    canGuestReserve: false,
    isActive: true,
    createdTime: '2025-01-25T16:45:16.2478345',
    floorId: 16,
    floor: {
      id: 16,
      name: '41 стол',
      priority: 5,
      isHostess: true,
      isActive: true,
      branchId: 1,
    },
    imageUrl: null,
    itemType: 'table17',
    itemClassId: null,
    typeId: null,
    isPosReserved: false,
    isPrintedBill: false,
    isPosMapped: false,
  },
];

export const setTableWithReserve = (table: ITable): ITableWithReserve => {
  return {
    ...table,
    reserves: [],
  };
};
